"""
twin_model.py
-------------
Predictive engine for the DigitalTwin.ai prototype.

This module consumes the synthetic data generated by data_simulator.py and
produces:
    - imputed station-event telemetry for sparse legacy/manual coverage
    - vehicle-level defect probabilities
    - probability-threshold analysis for false-alarm management
    - bottleneck alerts using SPC and Isolation Forest
    - station health, MTBF, OEE, and business-impact metrics

Run:
    python twin_model.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from pandas.api.types import is_numeric_dtype
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import average_precision_score, classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder


DATA_DIR = Path("data")
OUTPUT_DIR = Path("model_outputs")
TELEMETRY_COLUMNS = ["Torque_Nm", "Temperature_C", "Vibration_MM_S"]
QUALITY_GATE_STATION = 45


NON_FEATURE_COLUMNS = {
    "Vehicle_ID",
    "Vehicle_Global_Index",
    "End_of_Line_Quality",
    "Defect_Label",
    "Root_Cause_Label",
    "Delayed_Defect_Detection_Station",
    "Latent_Defect_Probability",
    "Station_12_Temperature_Signal",
    "Station_15_Vibration_Signal",
}


def make_one_hot_encoder() -> OneHotEncoder:
    """Return a version-compatible one-hot encoder."""
    try:
        return OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        return OneHotEncoder(handle_unknown="ignore", sparse=False)


def ensure_data_exists(data_dir: Path = DATA_DIR) -> None:
    """Generate synthetic data if the expected CSV files are missing."""
    required = [
        data_dir / "station_master.csv",
        data_dir / "synthetic_station_events.csv",
        data_dir / "vehicle_quality_summary.csv",
    ]
    if all(path.exists() for path in required):
        return

    from data_simulator import (
        DEFAULT_DAYS,
        DEFAULT_SEED,
        DEFAULT_SHIFTS_PER_DAY,
        DEFAULT_STATIONS,
        DEFAULT_UNITS_PER_SHIFT,
        build_station_master,
        generate_vehicle_contexts,
        simulate_station_events,
        write_outputs,
    )

    station_master = build_station_master(DEFAULT_STATIONS, DEFAULT_SEED)
    vehicles = generate_vehicle_contexts(
        days=DEFAULT_DAYS,
        shifts_per_day=DEFAULT_SHIFTS_PER_DAY,
        units_per_shift=DEFAULT_UNITS_PER_SHIFT,
        seed=DEFAULT_SEED,
    )
    station_events = simulate_station_events(
        station_master=station_master,
        vehicles=vehicles,
        units_per_shift=DEFAULT_UNITS_PER_SHIFT,
        seed=DEFAULT_SEED,
    )
    write_outputs(station_master, station_events, vehicles, data_dir)


def load_datasets(data_dir: Path = DATA_DIR) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Load station metadata, station-event telemetry, and vehicle quality rows."""
    ensure_data_exists(data_dir)

    station_master = pd.read_csv(data_dir / "station_master.csv")
    station_events = pd.read_csv(data_dir / "synthetic_station_events.csv")
    vehicle_summary = pd.read_csv(data_dir / "vehicle_quality_summary.csv")

    station_events["Timestamp"] = pd.to_datetime(station_events["Timestamp"])
    vehicle_summary["Shift_Start_Timestamp"] = pd.to_datetime(vehicle_summary["Shift_Start_Timestamp"])

    station_fields = station_master[
        [
            "Station_ID",
            "Operation",
            "Baseline_Cycle_Time",
            "Is_Quality_Gate",
        ]
    ]
    station_events = station_events.merge(station_fields, on="Station_ID", how="left")

    vehicle_fields = vehicle_summary[
        [
            "Vehicle_ID",
            "Vehicle_Global_Index",
            "Production_Day",
            "Unit_In_Shift",
            "Model_Complexity_Factor",
            "Latent_Defect_Probability",
        ]
    ]
    station_events = station_events.merge(vehicle_fields, on="Vehicle_ID", how="left")

    return station_master, station_events, vehicle_summary


def impute_station_telemetry(station_events: pd.DataFrame) -> pd.DataFrame:
    """
    Impute telemetry gaps while preserving missingness as a model feature.

    Strategy:
        1. Use station-level medians where a station has enough history.
        2. Fall back to process-area medians.
        3. Fall back to global medians.
        4. Add explicit missingness and coverage flags.
    """
    df = station_events.copy()

    for column in TELEMETRY_COLUMNS:
        missing = df[column].isna()
        station_median = df.groupby("Station_ID")[column].transform("median")
        area_median = df.groupby("Process_Area")[column].transform("median")
        global_median = df[column].median()
        if pd.isna(global_median):
            global_median = 0.0

        imputed = df[column].copy()
        source = pd.Series("measured", index=df.index, dtype="object")

        station_fill = missing & station_median.notna()
        imputed = imputed.where(~station_fill, station_median)
        source.loc[station_fill] = "station_median"

        still_missing = imputed.isna()
        area_fill = still_missing & area_median.notna()
        imputed = imputed.where(~area_fill, area_median)
        source.loc[area_fill] = "process_area_median"

        still_missing = imputed.isna()
        imputed = imputed.fillna(global_median)
        source.loc[still_missing] = "global_median"

        df[f"{column}_Was_Missing"] = missing.astype(int)
        df[f"{column}_Imputed"] = imputed.astype(float)
        df[f"{column}_Imputation_Source"] = source

    missing_flags = [f"{column}_Was_Missing" for column in TELEMETRY_COLUMNS]
    df["Any_Telemetry_Missing"] = df[missing_flags].max(axis=1)
    df["Sparse_Coverage_Flag"] = df["Sensor_Coverage"].isin(["legacy", "manual_check"]).astype(int)
    df["Legacy_Or_Manual_Imputed"] = (
        (df["Sparse_Coverage_Flag"] == 1) & (df["Any_Telemetry_Missing"] == 1)
    ).astype(int)

    return df


def build_vehicle_features(
    imputed_events: pd.DataFrame,
    vehicle_summary: pd.DataFrame,
    quality_gate_station: int = QUALITY_GATE_STATION,
) -> pd.DataFrame:
    """Aggregate upstream station events into one model row per vehicle."""
    upstream = imputed_events[imputed_events["Station_Number"] < quality_gate_station].copy()

    vehicle_agg = upstream.groupby("Vehicle_ID").agg(
        Cycle_Time_Mean=("Cycle_Time", "mean"),
        Cycle_Time_Std=("Cycle_Time", "std"),
        Cycle_Time_Max=("Cycle_Time", "max"),
        Cycle_Time_P95=("Cycle_Time", lambda values: values.quantile(0.95)),
        Torque_Mean=("Torque_Nm_Imputed", "mean"),
        Torque_Max=("Torque_Nm_Imputed", "max"),
        Temperature_Mean=("Temperature_C_Imputed", "mean"),
        Temperature_Max=("Temperature_C_Imputed", "max"),
        Vibration_Mean=("Vibration_MM_S_Imputed", "mean"),
        Vibration_Max=("Vibration_MM_S_Imputed", "max"),
        Torque_Missing_Rate=("Torque_Nm_Was_Missing", "mean"),
        Temperature_Missing_Rate=("Temperature_C_Was_Missing", "mean"),
        Vibration_Missing_Rate=("Vibration_MM_S_Was_Missing", "mean"),
        Sparse_Coverage_Rate=("Sparse_Coverage_Flag", "mean"),
        Legacy_Or_Manual_Imputed_Rate=("Legacy_Or_Manual_Imputed", "mean"),
        Telemetry_Confidence_Mean=("Telemetry_Confidence", "mean"),
    )

    area_cycle = upstream.pivot_table(
        index="Vehicle_ID",
        columns="Process_Area",
        values="Cycle_Time",
        aggfunc="mean",
    )
    area_cycle.columns = [
        f"{str(area).replace(' ', '_')}_Cycle_Time_Mean" for area in area_cycle.columns
    ]

    station_12 = (
        upstream[upstream["Station_Number"] == 12]
        .set_index("Vehicle_ID")[["Temperature_C_Imputed", "Cycle_Time"]]
        .rename(
            columns={
                "Temperature_C_Imputed": "ST12_Temperature_C",
                "Cycle_Time": "ST12_Cycle_Time",
            }
        )
    )
    station_15 = (
        upstream[upstream["Station_Number"] == 15]
        .set_index("Vehicle_ID")[["Vibration_MM_S_Imputed", "Cycle_Time"]]
        .rename(
            columns={
                "Vibration_MM_S_Imputed": "ST15_Vibration_MM_S",
                "Cycle_Time": "ST15_Cycle_Time",
            }
        )
    )

    features = vehicle_agg.join(area_cycle, how="left").join(station_12, how="left").join(station_15, how="left")
    features = features.reset_index()

    features["ST12_Temperature_Excess"] = (features["ST12_Temperature_C"] - 42.0).clip(lower=0)
    features["ST15_Vibration_Excess"] = (features["ST15_Vibration_MM_S"] - 3.1).clip(lower=0)
    features["ST12_ST15_Interaction"] = (
        features["ST12_Temperature_Excess"] * features["ST15_Vibration_Excess"]
    )

    vehicle_context = vehicle_summary[
        [
            "Vehicle_ID",
            "Vehicle_Global_Index",
            "Production_Day",
            "Shift",
            "Unit_In_Shift",
            "Vehicle_Model",
            "Model_Complexity_Factor",
            "End_of_Line_Quality",
            "Root_Cause_Label",
            "Delayed_Defect_Detection_Station",
            "Latent_Defect_Probability",
            "Station_12_Temperature_Signal",
            "Station_15_Vibration_Signal",
        ]
    ]
    features = features.merge(vehicle_context, on="Vehicle_ID", how="left")
    features["Defect_Label"] = (features["End_of_Line_Quality"] == "Fail").astype(int)

    return features


def model_feature_columns(features: pd.DataFrame) -> tuple[list[str], list[str]]:
    """Return numeric and categorical feature columns after excluding labels and metadata."""
    candidate_columns = [column for column in features.columns if column not in NON_FEATURE_COLUMNS]
    numeric = [column for column in candidate_columns if is_numeric_dtype(features[column])]
    categorical = [column for column in candidate_columns if column not in numeric]
    return numeric, categorical


def threshold_table(
    y_true: np.ndarray,
    probabilities: np.ndarray,
    thresholds: tuple[float, ...] = (0.15, 0.25, 0.35, 0.50, 0.65),
) -> list[dict[str, float]]:
    """Evaluate alert volume, precision, recall, and false-alarm rate by threshold."""
    y_bool = y_true.astype(bool)
    positive_count = int(y_bool.sum())
    rows: list[dict[str, float]] = []

    for threshold in thresholds:
        predicted = probabilities >= threshold
        alert_count = int(predicted.sum())
        true_positive_count = int((predicted & y_bool).sum())
        false_positive_count = alert_count - true_positive_count

        precision = true_positive_count / alert_count if alert_count else 0.0
        recall = true_positive_count / positive_count if positive_count else 0.0
        false_alarm_rate = false_positive_count / alert_count if alert_count else 0.0

        rows.append(
            {
                "threshold": float(threshold),
                "alerts": float(alert_count),
                "true_positives": float(true_positive_count),
                "precision": float(precision),
                "recall": float(recall),
                "false_alarm_rate": float(false_alarm_rate),
            }
        )

    return rows


def train_defect_model(
    features: pd.DataFrame,
    random_state: int = 42,
) -> tuple[Pipeline, dict[str, Any], pd.DataFrame]:
    """Train a Random Forest defect classifier and return validation metrics."""
    numeric_features, categorical_features = model_feature_columns(features)

    X = features[numeric_features + categorical_features]
    y = features["Defect_Label"].astype(int)

    if y.nunique() < 2:
        raise ValueError("Defect model needs at least one pass and one fail example.")

    stratify = y if y.value_counts().min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=random_state,
        stratify=stratify,
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("numeric", SimpleImputer(strategy="median"), numeric_features),
            (
                "categorical",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="most_frequent")),
                        ("onehot", make_one_hot_encoder()),
                    ]
                ),
                categorical_features,
            ),
        ],
        remainder="drop",
    )

    classifier = RandomForestClassifier(
        n_estimators=400,
        min_samples_leaf=3,
        class_weight="balanced_subsample",
        random_state=random_state,
        n_jobs=-1,
    )

    model = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("classifier", classifier),
        ]
    )
    model.fit(X_train, y_train)

    probabilities = model.predict_proba(X_test)[:, 1]
    predicted = (probabilities >= 0.35).astype(int)

    feature_names = model.named_steps["preprocessor"].get_feature_names_out()
    importances = model.named_steps["classifier"].feature_importances_
    importance_table = (
        pd.DataFrame(
            {
                "feature": [name.replace("numeric__", "").replace("categorical__", "") for name in feature_names],
                "importance": importances,
            }
        )
        .sort_values("importance", ascending=False)
        .head(15)
    )

    metrics: dict[str, Any] = {
        "roc_auc": float(roc_auc_score(y_test, probabilities)),
        "average_precision": float(average_precision_score(y_test, probabilities)),
        "positive_rate": float(y.mean()),
        "validation_rows": int(len(y_test)),
        "defect_rows": int(y.sum()),
        "feature_columns": numeric_features + categorical_features,
        "threshold_table": threshold_table(y_test.to_numpy(), probabilities),
        "classification_report_at_0_35": classification_report(
            y_test,
            predicted,
            output_dict=True,
            zero_division=0,
        ),
        "top_features": importance_table.to_dict(orient="records"),
    }

    return model, metrics, importance_table


def likely_driver(row: pd.Series) -> str:
    """Human-readable likely driver for the dashboard and CSV output."""
    if row.get("ST12_ST15_Interaction", 0) > 1.4:
        return "ST-12 temperature x ST-15 vibration"
    if row.get("Cycle_Time_P95", 0) > 92:
        return "High upstream cycle-time variation"
    if row.get("Legacy_Or_Manual_Imputed_Rate", 0) > 0.20:
        return "Low-confidence sparse telemetry"
    return "Distributed process variation"


def score_defect_risk(
    model: Pipeline,
    features: pd.DataFrame,
    threshold: float = 0.35,
) -> pd.DataFrame:
    """Score every vehicle and add high-risk alert flags."""
    numeric_features, categorical_features = model_feature_columns(features)
    probabilities = model.predict_proba(features[numeric_features + categorical_features])[:, 1]

    scored = features.copy()
    scored["Defect_Probability"] = probabilities
    scored["Risk_Percent"] = scored["Defect_Probability"] * 100.0
    scored["High_Risk_Alert"] = scored["Defect_Probability"] >= threshold
    scored["Alert_Threshold"] = threshold
    scored["Inspection_Priority"] = scored["Defect_Probability"].rank(
        method="first",
        ascending=False,
    ).astype(int)
    scored["Likely_Driver"] = scored.apply(likely_driver, axis=1)

    columns = [
        "Vehicle_ID",
        "Vehicle_Global_Index",
        "Production_Day",
        "Shift",
        "Unit_In_Shift",
        "Vehicle_Model",
        "Defect_Probability",
        "Risk_Percent",
        "High_Risk_Alert",
        "Alert_Threshold",
        "Inspection_Priority",
        "Likely_Driver",
        "End_of_Line_Quality",
        "Defect_Label",
        "Root_Cause_Label",
        "ST12_Temperature_C",
        "ST15_Vibration_MM_S",
        "ST12_ST15_Interaction",
        "Telemetry_Confidence_Mean",
        "Legacy_Or_Manual_Imputed_Rate",
    ]

    return scored[columns].sort_values("Defect_Probability", ascending=False).reset_index(drop=True)


def detect_bottlenecks(
    imputed_events: pd.DataFrame,
    random_state: int = 42,
    z_threshold: float = 2.7,
    contamination: float = 0.035,
) -> pd.DataFrame:
    """Detect bottlenecks with station-normalized SPC and Isolation Forest."""
    df = imputed_events.copy()

    station_stats = df.groupby("Station_ID").agg(
        Station_Cycle_Median=("Cycle_Time", "median"),
        Station_Cycle_Q25=("Cycle_Time", lambda values: values.quantile(0.25)),
        Station_Cycle_Q75=("Cycle_Time", lambda values: values.quantile(0.75)),
        Station_Cycle_Std=("Cycle_Time", "std"),
    )
    station_stats["Robust_Cycle_Std"] = (
        (station_stats["Station_Cycle_Q75"] - station_stats["Station_Cycle_Q25"]) / 1.349
    )
    station_stats["Robust_Cycle_Std"] = station_stats["Robust_Cycle_Std"].replace(0, np.nan)
    station_stats["Robust_Cycle_Std"] = station_stats["Robust_Cycle_Std"].fillna(
        station_stats["Station_Cycle_Std"]
    )
    station_stats["Robust_Cycle_Std"] = station_stats["Robust_Cycle_Std"].fillna(1.0)

    df = df.merge(station_stats[["Station_Cycle_Median", "Robust_Cycle_Std"]], on="Station_ID", how="left")
    df["Cycle_Z_Score"] = (
        (df["Cycle_Time"] - df["Station_Cycle_Median"]) / df["Robust_Cycle_Std"].replace(0, np.nan)
    ).fillna(0.0)
    df["Cycle_Time_Over_Baseline"] = (
        df["Cycle_Time"] - df["Baseline_Cycle_Time"]
    ).fillna(0.0)
    df["Excess_Cycle_Time"] = df["Cycle_Time_Over_Baseline"].clip(lower=0)
    df["SPC_Bottleneck_Flag"] = (df["Cycle_Z_Score"] >= z_threshold) & (df["Excess_Cycle_Time"] >= 5.0)

    iso_features = df[
        [
            "Cycle_Z_Score",
            "Cycle_Time_Over_Baseline",
            "Telemetry_Confidence",
            "Any_Telemetry_Missing",
        ]
    ].fillna(0.0)
    iso = IsolationForest(
        n_estimators=250,
        contamination=contamination,
        random_state=random_state,
    )
    iso_label = iso.fit_predict(iso_features)
    df["IsolationForest_Bottleneck_Flag"] = (iso_label == -1) & (df["Cycle_Z_Score"] >= 1.8)
    df["Bottleneck_Anomaly_Score"] = -iso.decision_function(iso_features)
    df["Bottleneck_Alert"] = df["SPC_Bottleneck_Flag"] | df["IsolationForest_Bottleneck_Flag"]

    df["Remaining_Units_In_Shift"] = 75 - df["Unit_In_Shift"].fillna(75)
    df["Projected_Delay_Minutes"] = (
        df["Excess_Cycle_Time"] * df["Remaining_Units_In_Shift"].clip(lower=0) / 60.0
    )
    df["Estimated_Queued_Vehicles"] = (
        df["Excess_Cycle_Time"] * 6.0 / df["Baseline_Cycle_Time"].replace(0, np.nan)
    ).fillna(0.0)

    alert_columns = [
        "Vehicle_ID",
        "Vehicle_Global_Index",
        "Production_Day",
        "Shift",
        "Unit_In_Shift",
        "Station_ID",
        "Station_Number",
        "Process_Area",
        "Operation",
        "Timestamp",
        "Sensor_Coverage",
        "Cycle_Time",
        "Baseline_Cycle_Time",
        "Cycle_Z_Score",
        "Excess_Cycle_Time",
        "Telemetry_Confidence",
        "SPC_Bottleneck_Flag",
        "IsolationForest_Bottleneck_Flag",
        "Bottleneck_Anomaly_Score",
        "Bottleneck_Alert",
        "Projected_Delay_Minutes",
        "Estimated_Queued_Vehicles",
    ]
    return df[alert_columns].sort_values(["Vehicle_Global_Index", "Station_Number"]).reset_index(drop=True)


def station_snapshot_at(
    bottleneck_events: pd.DataFrame,
    station_master: pd.DataFrame,
    current_vehicle_index: int | None = None,
    lookback_vehicles: int = 30,
) -> pd.DataFrame:
    """Return latest station status up to a selected vehicle index."""
    df = bottleneck_events.copy()
    if current_vehicle_index is None:
        current_vehicle_index = int(df["Vehicle_Global_Index"].max())

    history = df[df["Vehicle_Global_Index"] <= current_vehicle_index].copy()
    if history.empty:
        history = df.copy()

    latest = (
        history.sort_values(["Vehicle_Global_Index", "Station_Number"])
        .groupby("Station_ID")
        .tail(1)
    )
    active_window = df[
        (df["Vehicle_Global_Index"] >= current_vehicle_index - lookback_vehicles)
        & (df["Vehicle_Global_Index"] <= current_vehicle_index)
        & (df["Bottleneck_Alert"])
    ]
    active_alerts = active_window.groupby("Station_ID").agg(
        Window_Alert_Count=("Bottleneck_Alert", "sum"),
        Window_Max_Z=("Cycle_Z_Score", "max"),
        Window_Max_Delay_Minutes=("Projected_Delay_Minutes", "max"),
    )

    snapshot = station_master.merge(
        latest[
            [
                "Station_ID",
                "Vehicle_ID",
                "Timestamp",
                "Cycle_Time",
                "Cycle_Z_Score",
                "Excess_Cycle_Time",
                "Telemetry_Confidence",
                "Bottleneck_Alert",
            ]
        ],
        on="Station_ID",
        how="left",
    )
    snapshot = snapshot.merge(active_alerts, on="Station_ID", how="left")
    snapshot["Window_Alert_Count"] = snapshot["Window_Alert_Count"].fillna(0)
    snapshot["Window_Max_Z"] = snapshot["Window_Max_Z"].fillna(0)
    snapshot["Window_Max_Delay_Minutes"] = snapshot["Window_Max_Delay_Minutes"].fillna(0)

    snapshot["Station_Status"] = np.select(
        [
            snapshot["Window_Max_Z"] >= 3.5,
            snapshot["Window_Alert_Count"] > 0,
            snapshot["Sensor_Coverage"].isin(["legacy", "manual_check"]),
        ],
        ["critical", "watch", "low_confidence"],
        default="nominal",
    )
    snapshot["Confidence_Band"] = np.select(
        [
            snapshot["Sensor_Coverage"] == "modern",
            snapshot["Sensor_Coverage"] == "partial",
        ],
        ["high", "medium"],
        default="low",
    )
    return snapshot.sort_values("Station_Number")


def compute_station_health(
    imputed_events: pd.DataFrame,
    bottleneck_events: pd.DataFrame,
) -> pd.DataFrame:
    """Summarize station health and approximate MTBF from alert clusters."""
    health = imputed_events.groupby("Station_ID").agg(
        Station_Number=("Station_Number", "first"),
        Process_Area=("Process_Area", "first"),
        Operation=("Operation", "first"),
        Sensor_Coverage=("Sensor_Coverage", "first"),
        Avg_Cycle_Time=("Cycle_Time", "mean"),
        P95_Cycle_Time=("Cycle_Time", lambda values: values.quantile(0.95)),
        Avg_Telemetry_Confidence=("Telemetry_Confidence", "mean"),
        Missing_Telemetry_Rate=("Any_Telemetry_Missing", "mean"),
    )

    alert_rows = bottleneck_events[bottleneck_events["Bottleneck_Alert"]].copy()
    alert_summary = alert_rows.groupby("Station_ID").agg(
        Bottleneck_Alert_Count=("Bottleneck_Alert", "sum"),
        Max_Cycle_Z=("Cycle_Z_Score", "max"),
        Total_Projected_Delay_Minutes=("Projected_Delay_Minutes", "sum"),
    )

    mtbf_records: list[dict[str, Any]] = []
    for station_id, group in alert_rows.groupby("Station_ID"):
        ordered = group.sort_values("Vehicle_Global_Index").copy()
        if ordered.empty:
            continue
        ordered["New_Cluster"] = ordered["Vehicle_Global_Index"].diff().fillna(99) > 4
        ordered["Cluster_ID"] = ordered["New_Cluster"].cumsum()
        cluster_starts = ordered.groupby("Cluster_ID")["Timestamp"].min().sort_values()
        if len(cluster_starts) > 1:
            mtbf_hours = cluster_starts.diff().dropna().dt.total_seconds().mean() / 3600.0
        else:
            mtbf_hours = np.nan
        mtbf_records.append(
            {
                "Station_ID": station_id,
                "Failure_Event_Count": int(len(cluster_starts)),
                "MTBF_Hours": mtbf_hours,
            }
        )

    mtbf = pd.DataFrame(mtbf_records)
    if mtbf.empty:
        mtbf = pd.DataFrame(columns=["Station_ID", "Failure_Event_Count", "MTBF_Hours"])

    health = health.join(alert_summary, how="left").reset_index()
    health = health.merge(mtbf, on="Station_ID", how="left")
    fill_columns = [
        "Bottleneck_Alert_Count",
        "Max_Cycle_Z",
        "Total_Projected_Delay_Minutes",
        "Failure_Event_Count",
    ]
    health[fill_columns] = health[fill_columns].fillna(0)
    return health.sort_values(["Bottleneck_Alert_Count", "Max_Cycle_Z"], ascending=False)


def compute_business_metrics(
    imputed_events: pd.DataFrame,
    vehicle_summary: pd.DataFrame,
    scored_vehicles: pd.DataFrame,
) -> dict[str, float]:
    """Compute OEE roll-up and savings estimate from targeted defect prevention."""
    total_vehicles = len(vehicle_summary)
    failed_vehicles = int((vehicle_summary["End_of_Line_Quality"] == "Fail").sum())
    pass_rate = 1.0 - failed_vehicles / total_vehicles

    baseline_seconds = imputed_events["Baseline_Cycle_Time"].sum()
    actual_seconds = imputed_events["Cycle_Time"].sum()
    excess_seconds = (imputed_events["Cycle_Time"] - imputed_events["Baseline_Cycle_Time"]).clip(lower=0).sum()

    availability = 1.0 - min(0.18, excess_seconds / max(actual_seconds, 1.0) * 0.55)
    performance = min(1.0, baseline_seconds / max(actual_seconds, 1.0))
    quality = pass_rate
    oee = availability * performance * quality

    high_risk = scored_vehicles[scored_vehicles["High_Risk_Alert"]]
    true_positives = int(high_risk["Defect_Label"].sum())
    alert_count = int(len(high_risk))
    expected_random_hits = failed_vehicles * (alert_count / max(total_vehicles, 1))
    incremental_hits = max(0.0, true_positives - expected_random_hits)

    annual_volume = 250_000
    cost_per_defect = 500.0
    defect_rate = failed_vehicles / max(total_vehicles, 1)
    capture_quality = incremental_hits / max(failed_vehicles, 1)
    annual_savings_low = annual_volume * defect_rate * cost_per_defect * capture_quality * 0.35
    annual_savings_high = annual_volume * defect_rate * cost_per_defect * capture_quality * 0.55

    return {
        "total_vehicles": float(total_vehicles),
        "failed_vehicles": float(failed_vehicles),
        "defect_rate": float(defect_rate),
        "availability": float(availability),
        "performance": float(performance),
        "quality": float(quality),
        "oee": float(oee),
        "high_risk_alerts": float(alert_count),
        "true_positive_alerts": float(true_positives),
        "expected_random_hits": float(expected_random_hits),
        "incremental_defects_caught": float(incremental_hits),
        "estimated_annual_savings_low": float(annual_savings_low),
        "estimated_annual_savings_high": float(annual_savings_high),
    }


def json_safe(value: Any) -> Any:
    """Convert pandas/numpy values for JSON output."""
    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, list):
        return [json_safe(item) for item in value]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if pd.isna(value) if not isinstance(value, (dict, list, tuple, str)) else False:
        return None
    return value


def run_pipeline(
    data_dir: Path = DATA_DIR,
    output_dir: Path | None = OUTPUT_DIR,
    threshold: float = 0.35,
    random_state: int = 42,
) -> dict[str, Any]:
    """Execute the full Phase 3 predictive engine."""
    station_master, station_events, vehicle_summary = load_datasets(data_dir)
    imputed_events = impute_station_telemetry(station_events)
    features = build_vehicle_features(imputed_events, vehicle_summary)
    model, metrics, feature_importance = train_defect_model(features, random_state=random_state)
    scored_vehicles = score_defect_risk(model, features, threshold=threshold)
    bottleneck_events = detect_bottlenecks(imputed_events, random_state=random_state)
    station_health = compute_station_health(imputed_events, bottleneck_events)
    business_metrics = compute_business_metrics(imputed_events, vehicle_summary, scored_vehicles)

    if output_dir is not None:
        output_dir.mkdir(parents=True, exist_ok=True)
        scored_vehicles.to_csv(output_dir / "defect_risk_scores.csv", index=False)
        bottleneck_events[bottleneck_events["Bottleneck_Alert"]].to_csv(
            output_dir / "bottleneck_alerts.csv",
            index=False,
        )
        station_health.to_csv(output_dir / "station_health.csv", index=False)
        features.to_csv(output_dir / "vehicle_features.csv", index=False)
        with (output_dir / "model_metrics.json").open("w", encoding="utf-8") as file:
            json.dump(
                json_safe(
                    {
                        "defect_model": metrics,
                        "business_metrics": business_metrics,
                    }
                ),
                file,
                indent=2,
            )

    return {
        "station_master": station_master,
        "station_events": station_events,
        "imputed_events": imputed_events,
        "vehicle_summary": vehicle_summary,
        "features": features,
        "model": model,
        "metrics": metrics,
        "feature_importance": feature_importance,
        "scored_vehicles": scored_vehicles,
        "bottleneck_events": bottleneck_events,
        "station_health": station_health,
        "business_metrics": business_metrics,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the DigitalTwin.ai predictive engine.")
    parser.add_argument("--data-dir", type=Path, default=DATA_DIR)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    parser.add_argument("--threshold", type=float, default=0.35)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = run_pipeline(
        data_dir=args.data_dir,
        output_dir=args.output_dir,
        threshold=args.threshold,
        random_state=args.seed,
    )

    metrics = result["metrics"]
    business = result["business_metrics"]
    scored = result["scored_vehicles"]
    alerts = result["bottleneck_events"]

    high_risk_count = int(scored["High_Risk_Alert"].sum())
    bottleneck_count = int(alerts["Bottleneck_Alert"].sum())

    print("DigitalTwin.ai predictive engine complete.")
    print(f"ROC-AUC: {metrics['roc_auc']:.3f}")
    print(f"Average precision: {metrics['average_precision']:.3f}")
    print(f"High-risk vehicle alerts at threshold {args.threshold:.2f}: {high_risk_count}")
    print(f"Bottleneck alert rows: {bottleneck_count}")
    print(f"OEE roll-up: {business['oee']:.3f}")
    print(f"Outputs written to: {args.output_dir.resolve()}")


if __name__ == "__main__":
    main()
